<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\DotnetFastMCP\src\FastMCP\FastMCP.csproj" />
    <ProjectReference Include="..\..\FashionPipeline.Core\FashionPipeline.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d724024f-2a64-46f8-99c7-58e6d9162181</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Templates\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
