<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\DotnetFastMCP\src\FastMCP\FastMCP.csproj" />
    <ProjectReference Include="..\..\FashionPipeline.Core\FashionPipeline.Core.csproj" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.20.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d53c6f5c-6b7a-481c-902c-7b176fbea317</UserSecretsId>
  </PropertyGroup>

</Project>
